version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FirstDynamoDB"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-p3h36ndnwqob"
s3_prefix = "FirstDynamoDB"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
